// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEG9cVMtLt0Xnc5QhjEGmU3TOzGSFjmL8',
    appId: '1:944312759456:web:a7ebe019d96de0f7fc45c5',
    messagingSenderId: '944312759456',
    projectId: 'chat-f89cb',
    authDomain: 'chat-f89cb.firebaseapp.com',
    storageBucket: 'chat-f89cb.appspot.com',
    measurementId: 'G-6XWMSRQJ4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6maNH4DhA2xbI_RUJ_e1CoGCjtYRG_iI',
    appId: '1:944312759456:android:7e22f0ad3ddb34a8fc45c5',
    messagingSenderId: '944312759456',
    projectId: 'chat-f89cb',
    storageBucket: 'chat-f89cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyi4rNvFfh-sZpkIpMBZPAP4tyFMn3TbI',
    appId: '1:944312759456:ios:5406ecfb7dd6b971fc45c5',
    messagingSenderId: '944312759456',
    projectId: 'chat-f89cb',
    storageBucket: 'chat-f89cb.appspot.com',
    iosBundleId: 'com.example.chatMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyi4rNvFfh-sZpkIpMBZPAP4tyFMn3TbI',
    appId: '1:944312759456:ios:57268c79be1cde4ffc45c5',
    messagingSenderId: '944312759456',
    projectId: 'chat-f89cb',
    storageBucket: 'chat-f89cb.appspot.com',
    iosBundleId: 'com.example.chatMobile.RunnerTests',
  );
}
